GET http://localhost:18080 HTTP/1.1

###

GET http://localhost:18080/contact/goke HTTP/1.1

###

POST http://localhost:18080 HTTP/1.1

###
POST http://localhost:18080/rest_test HTTP/1.1

###
POST http://localhost:18080/api/contactx HTTP/1.1

{
    "id":8,
    "name": "Bax",
    "phone": "2394477"
}
